# Site settings
title: Serviços de Enfermagem ao Domicilio - Sintra - Cascais - Cuidar no lar
email: geral@cuidarnolar.pt
description: > # Prestação de cuidados individualizados e diferenciados no seu lar.Disponibilizamos aos nossos utentes um vasto leque de serviços ao domicílio. Proporcionar bem-estar, conforto e qualidade de vidas aos nossos utentes e suas famílias.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://cuidarnolar.pt" # the base hostname & protocol for your site

# User setting
owner: HILQ - Saúde Lda
email: geral@cuidarnolar.pt
facebook_username: Cuidar-no-Lar-1238194989536020
twitter_username:
#github_username:
linkedin_username:
address: 
  - line: RUA LUIS CAMÕES 307 TIRES
  - line: 2785-147, São Domingos de Rana
  # Feel free to add more lines here 
telephone: +351 964411438
copyright: Cuidarnolar.pt

# API settings
google_api_key: AIzaSyCXxmxCoFpGfjITpo0udVacnIIKQbdEuk0

# Build settings
markdown: kramdown
